train_file: '/home/ps/leijiayu/CODE/MedKLIP/Pretrain_MedKLIP_bce/data_file_more_label/train_data_path.json'
valid_file: '/home/ps/leijiayu/CODE/MedKLIP/Pretrain_MedKLIP_bce/data_file_more_label/val_data_path.json'
test_file: '/home/ps/leijiayu/CODE/MedKLIP/Pretrain_MedKLIP_bce/data_file_more_label/test_data_path.json'
label_file: '/home/ps/leijiayu/CODE/MedKLIP/Pretrain_MedKLIP_bce/data_file_more_label/label.npy'
disease_order: '/home/ps/leijiayu/CODE/MedKLIP/Pretrain_MedKLIP_bce/data_file_more_label/dis_order.json'

num_classes: 13
batch_size: 16
max_epochs: 100

input_W: 224
input_H: 224
input_D: 24

lr: 2e-4
weight_decay: 1e-5
amsgrad: True

patch_size: 16

vision_width: 768
fea_width: 197
# embed_dim: 256

dropout: 0.1
attribute_set_size: 1

optimizer: {opt: adamW, lr: 1e-4, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-4, epochs: 100, min_lr: 1e-5, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 5, cooldown_epochs: 0}





