4_image_encoder: false
H: 4
N: 4
alpha: 0.4
anatomy_order: /home/ps/leijiayu/CODE/MedKLIP/Pretrain_MedKLIP_bce/data_file_kad/anatomy_order.json
attention: false
attribute_set_size: 1
batch_size: 32
class_p: /home/ps/leijiayu/CODE/MedKLIP/Pretrain_MedKLIP/data_file/class_p.json
conv1_t_size: 7
conv1_t_stride: 1
d_model: 768
disease_book: /home/ps/leijiayu/CODE/MedKLIP/Pretrain_MedKLIP_bce/data_file_kad/dis_description.json
disease_order: /home/ps/leijiayu/CODE/MedKLIP/Pretrain_MedKLIP_bce/data_file_kad/dis_order.json
dropout: 0.1
exclude_class: false
fea_width: 197
gpu_id: [0]
image_res: 224
in_channels: 1
input_D: 16
input_H: 224
input_W: 224
kad: false
kad_loss_ratio: 0
la: false
la_alpha: 1
label_file: /home/ps/leijiayu/CODE/MedKLIP/Pretrain_MedKLIP_bce/data_file_kad/label.npy
mlm_probability: 0.15
model_depth: 34
model_type: resnet
momentum: 0.995
no_cl: false
no_cuda: false
no_max_pool: false
num_classes: 14
num_queries: 75
num_sentences: 12
num_tokens: 32
optimizer: {lr: 0.0001, opt: adamW, weight_decay: 0.02}
out_feature: 768
patch_size: 16
pretrain_path: /home/ps/leijiayu/CODE/MedKLIP/Pretrain_MedKLIP/models/pretrained_weights/resnet_34.pth
queue_size: 8192
report_observe: /home/ps/leijiayu/CODE/MedKLIP/Pretrain_MedKLIP_bce/data_file_kad/report_observe.npy
res_base_model: resnet34
resnet_shortcut: B
schedular: {cooldown_epochs: 0, decay_rate: 1, epochs: 100, lr: 0.0001, min_lr: 1e-05,
  sched: cosine, warmup_epochs: 5, warmup_lr: 1e-05}
seperate_classifier: true
shuffle_ratio: 0.5
temp: 0.07
test_batch_size: 32
test_file: /home/ps/leijiayu/CODE/MedKLIP/Pretrain_MedKLIP_bce/data_file_kad/test_data_path.json
text_encoder: xmcmic/Med-KEBERT
vision_width: 768
train_file: '/home/ps/leijiayu/CODE/MedKLIP/Pretrain_MedKLIP_bce/data_file_kad/fintune_train_data_path.json'
valid_file: '/home/ps/leijiayu/CODE/MedKLIP/Pretrain_MedKLIP_bce/data_file_kad/fintune_val_data_path.json'
